pipeline:
  run-tests:
    image: node:6.3.0
    commands:
      - npm install lodash
 
  
  frontend:
    image: node:5.3.0
    commands:
      - npm install
      - npm test
  backend:
    image: golang:1.5
    commands:
      - go get
      - go build
      - go test
